### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: qml

### ISSUE THREAD

**Issue by hpfn** [hipersayanX/webcamoid#26]
Hi,

I'm working on a debian package for webcamoid be part of Debian repositories.

There is a missing dependence in debian/control file:  qtdeclarative5-dev.

I will report a few more things.

regards,
Herbert

**Comment by hipersayanX** [comment]
Nice, thanks a lot! :+1:

**Comment by hipersayanX** [comment]
Fixed in 7.0.0, closing.
