### ISSUE TITLE
names in debian/control

### ISSUE THREAD

**Issue by hpfn** [hipersayanX/webcamoid#28]
Hi,

The files on Build-Depends field are *-ffmpeg-*.

I believe the -ffmpeg- part should be removed. The result of a search
with apt-cache search (sid):

# apt-cache search libavdevice
libavdevice-dev - FFmpeg library for handling input and output devices - development files
libavdevice-ffmpeg56 - FFmpeg library for handling input and output devices - runtime files

regards,
Herbert

**Comment by hipersayanX** [comment]
Issue fixed in latest release, closing.
