### ISSUE TITLE
debian directory in tarball

### ISSUE THREAD

**Issue by hpfn** [hipersayanX/webcamoid#29]
Hi,

I would like to ask some things.

Can you remove the debian directory from the tarball ?
If is important to keep it in the repository, can it be in a
different branch ?

The binary webcamoid needs a manpage. I will do one,
but feel free to do if you want.

regards,
Herbert

**Comment by hipersayanX** [comment]
Hi, i moved *debian* folder to [ports](https://github.com/hipersayanX/webcamoid/tree/master/ports/debian), and added a [man page](https://github.com/hipersayanX/webcamoid/blob/master/doc/man/man1/webcamoid.1).

**Comment by hpfn** [comment]
On Mon, 09 Nov 2015 12:59:30 -0800
hipersayanX <notifications@github.com> wrote:

> Hi, i moved *debian* folder to [ports](https://github.com/hipersayanX/webcamoid/tree/master/ports/debian), and added a [man page](https://github.com/hipersayanX/webcamoid/blob/master/doc/man/man1/webcamoid.1).
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/hipersayanX/webcamoid/issues/29#issuecomment-155191302

Thanks!


regards,
-- 
Herbert Parentes Fortes Neto (hpfn)

**Comment by hipersayanX** [comment]
Fixed in latest release, closing.
